### ISSUE TITLE
Snap version doesn't match semgrep version

### ISSUE THREAD

**Issue by artivis** [iosifache/semgrep-snap#5]
The snap is currently at version `1.1` but ships semgrep version `1.50.0`. 
Not sure if this is intended but it is definitely misleading.

To currently check given #4,

```terminal
$snap run --shell semgrep
root@path$ semgrep --version
1.50.0
```

**Comment by iosifache** [comment]
Hi @artivis,

Thanks for your proposal! I agree that it can confuse the users. I made the modifications and will release a new version in a couple of minutes.

Thanks 🙌🏿!

**Comment by artivis** [comment]
@iosifache Thanks for the fixes.  
Rather than manually updating the version, I'd suggest to retrieve the version directly from the pip package, something along the lines of,

```yaml
# Identifier
name: semgrep

# Version of the snap retrieved from the pip package
adopt-info: semgrep

# Base snap
base: core22

# Maturity, either devel or stable
grade: stable

# Minimal access level, with permissions provided by the interfaces above
confinement: strict

# Build and run architectures
architectures:
  - build-on: [amd64]
  - build-on: [arm64]

# A Python part for "proxying" the wheel from PyPi
parts:
  semgrep:
    plugin: python
    source: .
    python-packages:
      - semgrep
    override-build: |
      craftctl default
      version="$(python3 -m pip show semgrep | sed -n 's|^Version: ||p')"
      craftctl set version="$version"
```

This, coupled with a github action to release the snap, makes this packaging mostly automated.
